//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RewriteMe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Presentation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Presentation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RewriteMe.Resources.Presentation", typeof(Presentation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}% accuracy).
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string ActivityIndicatorCaptionText {
            get {
                return ResourceManager.GetString("ActivityIndicatorCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API url.
        /// </summary>
        public static string ApiUrl {
            get {
                return ResourceManager.GetString("ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API url is saved.
        /// </summary>
        public static string ApiUrlSaved {
            get {
                return ResourceManager.GetString("ApiUrlSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is out of date and it might not working properly. Please update it..
        /// </summary>
        public static string ApplicationIsOutOfDateMessage {
            get {
                return ResourceManager.GetString("ApplicationIsOutOfDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voicipher.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voicipher - Log.
        /// </summary>
        public static string ApplicationTitleLog {
            get {
                return ResourceManager.GetString("ApplicationTitleLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App store seems to be unavailble. Please try again later..
        /// </summary>
        public static string AppStoreUnavailableErrorMessage {
            get {
                return ResourceManager.GetString("AppStoreUnavailableErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio files.
        /// </summary>
        public static string AudioFiles {
            get {
                return ResourceManager.GetString("AudioFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing seems to be unavailable. Please try again later..
        /// </summary>
        public static string BillingUnavailableErrorMessage {
            get {
                return ResourceManager.GetString("BillingUnavailableErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy more time.
        /// </summary>
        public static string BuyMoreTime {
            get {
                return ResourceManager.GetString("BuyMoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Deleting user account is irreversible. This will permanently delete your data. This action cannot be undone. If you want to continue, type &apos;{0}&apos; for confirmation..
        /// </summary>
        public static string DeleteUserAccountMessage {
            get {
                return ResourceManager.GetString("DeleteUserAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ~4€.
        /// </summary>
        public static string DescriptionFiveHours {
            get {
                return ResourceManager.GetString("DescriptionFiveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ~10€.
        /// </summary>
        public static string DescriptionTenHours {
            get {
                return ResourceManager.GetString("DescriptionTenHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer mode is activated.
        /// </summary>
        public static string DeveloperModeIsActivated {
            get {
                return ResourceManager.GetString("DeveloperModeIsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading... {0}%.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not supported on this device.
        /// </summary>
        public static string EmailIsNotSupported {
            get {
                return ResourceManager.GetString("EmailIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is already processing. Please contact us..
        /// </summary>
        public static string FileIsAlreadyProcessingErrorMessage {
            get {
                return ResourceManager.GetString("FileIsAlreadyProcessingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not completely uploaded. Please try again later..
        /// </summary>
        public static string FileIsNotUploadedErrorMessage {
            get {
                return ResourceManager.GetString("FileIsNotUploadedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not correctly uploaded. Please try again later..
        /// </summary>
        public static string FileItemSourceDatabaseUpdateErrorMessage {
            get {
                return ResourceManager.GetString("FileItemSourceDatabaseUpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Hours.
        /// </summary>
        public static string FiveHours {
            get {
                return ResourceManager.GetString("FiveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes max.
        /// </summary>
        public static string FiveMinutesOnly {
            get {
                return ResourceManager.GetString("FiveMinutesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter.
        /// </summary>
        public static string Highlighter {
            get {
                return ResourceManager.GetString("Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method is not supported. Please configure it first..
        /// </summary>
        public static string InAppBillingIsNotSupportedErrorMessage {
            get {
                return ResourceManager.GetString("InAppBillingIsNotSupportedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect data.
        /// </summary>
        public static string IncorrectUserInputErrorMessage {
            get {
                return ResourceManager.GetString("IncorrectUserInputErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file is invalid..
        /// </summary>
        public static string InvalidAudioFileErrorMessage {
            get {
                return ResourceManager.GetString("InvalidAudioFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech (Czech Republic).
        /// </summary>
        public static string Language_CS_CZ {
            get {
                return ResourceManager.GetString("Language_CS_CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (Germany).
        /// </summary>
        public static string Language_DE_DE {
            get {
                return ResourceManager.GetString("Language_DE_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Australia).
        /// </summary>
        public static string Language_EN_AU {
            get {
                return ResourceManager.GetString("Language_EN_AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (United Kingdom).
        /// </summary>
        public static string Language_EN_GB {
            get {
                return ResourceManager.GetString("Language_EN_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (United States).
        /// </summary>
        public static string Language_EN_US {
            get {
                return ResourceManager.GetString("Language_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (Spain).
        /// </summary>
        public static string Language_ES_ES {
            get {
                return ResourceManager.GetString("Language_ES_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French (France).
        /// </summary>
        public static string Language_FR_FR {
            get {
                return ResourceManager.GetString("Language_FR_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian (Hungary).
        /// </summary>
        public static string Language_HU_HU {
            get {
                return ResourceManager.GetString("Language_HU_HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian (Italy).
        /// </summary>
        public static string Language_IT_IT {
            get {
                return ResourceManager.GetString("Language_IT_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (Japan).
        /// </summary>
        public static string Language_JA_JP {
            get {
                return ResourceManager.GetString("Language_JA_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish (Poland).
        /// </summary>
        public static string Language_PL_PL {
            get {
                return ResourceManager.GetString("Language_PL_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Portugal).
        /// </summary>
        public static string Language_PT_PT {
            get {
                return ResourceManager.GetString("Language_PT_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian (Russia).
        /// </summary>
        public static string Language_RU_RU {
            get {
                return ResourceManager.GetString("Language_RU_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak (Slovakia).
        /// </summary>
        public static string Language_SK_SK {
            get {
                return ResourceManager.GetString("Language_SK_SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Mandarin, simplified).
        /// </summary>
        public static string Language_ZH {
            get {
                return ResourceManager.GetString("Language_ZH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Mandarin, simplified).
        /// </summary>
        public static string Language_ZH_CN {
            get {
                return ResourceManager.GetString("Language_ZH_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is not supported..
        /// </summary>
        public static string LanguageNotSupportedErrorMessage {
            get {
                return ResourceManager.GetString("LanguageNotSupportedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data.....
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available data.
        /// </summary>
        public static string NoAvailableData {
            get {
                return ResourceManager.GetString("NoAvailableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages.
        /// </summary>
        public static string NoAvailableMessages {
            get {
                return ResourceManager.GetString("NoAvailableMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files yet.
        /// </summary>
        public static string NoFilesMessage {
            get {
                return ResourceManager.GetString("NoFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recordings yet.
        /// </summary>
        public static string NoRecordingsMessage {
            get {
                return ResourceManager.GetString("NoRecordingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough minutes left. Please buy more time..
        /// </summary>
        public static string NotEnoughFreeMinutesInSubscriptionErrorMessage {
            get {
                return ResourceManager.GetString("NotEnoughFreeMinutesInSubscriptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems you are offline. Please check your internet connection..
        /// </summary>
        public static string OfflineErrorMessage {
            get {
                return ResourceManager.GetString("OfflineErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not connected to the internet. Please check your internet connection..
        /// </summary>
        public static string OfflineMessageText {
            get {
                return ResourceManager.GetString("OfflineMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hour.
        /// </summary>
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s only possible to transcribe one file at a time. Please wait till your transcription will be finished..
        /// </summary>
        public static string OneTranscriptionAtTimeErrorMessage {
            get {
                return ResourceManager.GetString("OneTranscriptionAtTimeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment seems to be invalid. Please try again later..
        /// </summary>
        public static string PaymentInvalidErrorMessage {
            get {
                return ResourceManager.GetString("PaymentInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment does not seem to be allowed. Please try again later..
        /// </summary>
        public static string PaymentNotAllowedErrorMessage {
            get {
                return ResourceManager.GetString("PaymentNotAllowedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data was not changed. Please try again later..
        /// </summary>
        public static string ProfileEditErrorMessage {
            get {
                return ResourceManager.GetString("ProfileEditErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this file &apos;{0}&apos;?.
        /// </summary>
        public static string PromptDeleteFileItemMessage {
            get {
                return ResourceManager.GetString("PromptDeleteFileItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase was processed incorrectly. Please contact us..
        /// </summary>
        public static string PurchaseProcessedIncorrectlyErrorMessage {
            get {
                return ResourceManager.GetString("PurchaseProcessedIncorrectlyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase was not processed. Please try again later..
        /// </summary>
        public static string PurchaseWasNotProcessedErrorMessage {
            get {
                return ResourceManager.GetString("PurchaseWasNotProcessedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording only.
        /// </summary>
        public static string RecordingOnly {
            get {
                return ResourceManager.GetString("RecordingOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings.
        /// </summary>
        public static string Recordings {
            get {
                return ResourceManager.GetString("Recordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register or sign in.
        /// </summary>
        public static string RegisterOrSignIn {
            get {
                return ResourceManager.GetString("RegisterOrSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please register to use Voicipher.
        /// </summary>
        public static string RegisterToUseApplication {
            get {
                return ResourceManager.GetString("RegisterToUseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription was purchased but it was not successfully registered. Please contact us..
        /// </summary>
        public static string RegistrationPurchaseBillingErrorMessage {
            get {
                return ResourceManager.GetString("RegistrationPurchaseBillingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time.
        /// </summary>
        public static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and transcribe.
        /// </summary>
        public static string SaveAndTranscribe {
            get {
                return ResourceManager.GetString("SaveAndTranscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        public static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in failed.
        /// </summary>
        public static string SignInFailed {
            get {
                return ResourceManager.GetString("SignInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in successful.
        /// </summary>
        public static string SignInSuccessful {
            get {
                return ResourceManager.GetString("SignInSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        public static string Slovak {
            get {
                return ResourceManager.GetString("Slovak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection was not established. Please try again later..
        /// </summary>
        public static string SpeechClientNotInitializedErrorMessage {
            get {
                return ResourceManager.GetString("SpeechClientNotInitializedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription was successfully purchased..
        /// </summary>
        public static string SubscriptionWasSuccessfullyPurchased {
            get {
                return ResourceManager.GetString("SubscriptionWasSuccessfullyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization is still in progress. Please try again later..
        /// </summary>
        public static string SynchronizationInProgressErrorMessage {
            get {
                return ResourceManager.GetString("SynchronizationInProgressErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is under maintenance. Please try again later..
        /// </summary>
        public static string SystemIsUnderMaintenanceErrorMessage {
            get {
                return ResourceManager.GetString("SystemIsUnderMaintenanceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Hours.
        /// </summary>
        public static string TenHours {
            get {
                return ResourceManager.GetString("TenHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribe.
        /// </summary>
        public static string Transcribe {
            get {
                return ResourceManager.GetString("Transcribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribe audio source was not found. Please contact us..
        /// </summary>
        public static string TranscribeAudioSourceNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("TranscribeAudioSourceNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribed.
        /// </summary>
        public static string Transcribed {
            get {
                return ResourceManager.GetString("Transcribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; was not successfully transcribed. Please try it again or contact us..
        /// </summary>
        public static string TranscriptionErrorMessage {
            get {
                return ResourceManager.GetString("TranscriptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the audio file..
        /// </summary>
        public static string UnableToLoadAudioFile {
            get {
                return ResourceManager.GetString("UnableToLoadAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a permission to upload a file. Please try again later..
        /// </summary>
        public static string UnauthorizedErrorMessage {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is unreachable. Please try again later..
        /// </summary>
        public static string UnreachableServerErrorMessage {
            get {
                return ResourceManager.GetString("UnreachableServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems like the uploaded file is corrupted. Please try to upload it again..
        /// </summary>
        public static string UploadedFileIsCorruptedErrorMessage {
            get {
                return ResourceManager.GetString("UploadedFileIsCorruptedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file is not supported..
        /// </summary>
        public static string UploadedFileNotSupportedErrorMessage {
            get {
                return ResourceManager.GetString("UploadedFileNotSupportedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload might take some time. Please do not turn off the application, otherwise your file might not be uploaded..
        /// </summary>
        public static string UploadFileItemInfoMessage {
            get {
                return ResourceManager.GetString("UploadFileItemInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was not correctly deleted. Please try again later..
        /// </summary>
        public static string UserAccountDeletionErrorMessage {
            get {
                return ResourceManager.GetString("UserAccountDeletionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration.
        /// </summary>
        public static string UserRegistration {
            get {
                return ResourceManager.GetString("UserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration failed.
        /// </summary>
        public static string UserRegistrationFailed {
            get {
                return ResourceManager.GetString("UserRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
