// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RewriteMe.Domain.WebApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AudioSource
    {
        /// <summary>
        /// Initializes a new instance of the AudioSource class.
        /// </summary>
        public AudioSource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AudioSource class.
        /// </summary>
        public AudioSource(System.Guid? id = default(System.Guid?), System.Guid? fileItemId = default(System.Guid?), string contentType = default(string), int? version = default(int?))
        {
            Id = id;
            FileItemId = fileItemId;
            ContentType = contentType;
            Version = version;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileItemId")]
        public System.Guid? FileItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contentType")]
        public string ContentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public int? Version { get; set; }

    }
}
