// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RewriteMe.Domain.WebApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ContactFormModel
    {
        /// <summary>
        /// Initializes a new instance of the ContactFormModel class.
        /// </summary>
        public ContactFormModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ContactFormModel class.
        /// </summary>
        public ContactFormModel(string name = default(string), string email = default(string), string message = default(string))
        {
            Name = name;
            Email = email;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
