// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RewriteMe.Domain.WebApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DeletedFileItemModel
    {
        /// <summary>
        /// Initializes a new instance of the DeletedFileItemModel class.
        /// </summary>
        public DeletedFileItemModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeletedFileItemModel class.
        /// </summary>
        public DeletedFileItemModel(System.Guid id, System.DateTime deletedDate)
        {
            Id = id;
            DeletedDate = deletedDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deletedDate")]
        public System.DateTime DeletedDate { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
