// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RewriteMe.Domain.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FileItem
    {
        /// <summary>
        /// Initializes a new instance of the FileItem class.
        /// </summary>
        public FileItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FileItem class.
        /// </summary>
        public FileItem(System.Guid id, string name, string fileName, string language, string recognitionStateString, long totalTimeTicks, long transcribedTimeTicks, System.DateTime dateCreated, System.DateTime dateUpdated, bool isDeleted, System.DateTime? dateProcessed = default(System.DateTime?))
        {
            Id = id;
            Name = name;
            FileName = fileName;
            Language = language;
            RecognitionStateString = recognitionStateString;
            TotalTimeTicks = totalTimeTicks;
            TranscribedTimeTicks = transcribedTimeTicks;
            DateCreated = dateCreated;
            DateProcessed = dateProcessed;
            DateUpdated = dateUpdated;
            IsDeleted = isDeleted;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "language")]
        public string Language { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recognitionStateString")]
        public string RecognitionStateString { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalTimeTicks")]
        public long TotalTimeTicks { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transcribedTimeTicks")]
        public long TranscribedTimeTicks { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateCreated")]
        public System.DateTime DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateProcessed")]
        public System.DateTime? DateProcessed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateUpdated")]
        public System.DateTime DateUpdated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDeleted")]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (FileName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FileName");
            }
            if (Language == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Language");
            }
            if (RecognitionStateString == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RecognitionStateString");
            }
        }
    }
}
