// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RewriteMe.Domain.WebApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FileItem
    {
        /// <summary>
        /// Initializes a new instance of the FileItem class.
        /// </summary>
        public FileItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FileItem class.
        /// </summary>
        public FileItem(System.Guid? id = default(System.Guid?), string name = default(string), string fileName = default(string), string language = default(string), string recognitionState = default(string), string totalTimeString = default(string), System.DateTime? dateCreated = default(System.DateTime?), System.DateTime? dateProcessed = default(System.DateTime?), System.DateTime? dateUpdated = default(System.DateTime?), int? audioSourceVersion = default(int?), AudioSource audioSource = default(AudioSource))
        {
            Id = id;
            Name = name;
            FileName = fileName;
            Language = language;
            RecognitionState = recognitionState;
            TotalTimeString = totalTimeString;
            DateCreated = dateCreated;
            DateProcessed = dateProcessed;
            DateUpdated = dateUpdated;
            AudioSourceVersion = audioSourceVersion;
            AudioSource = audioSource;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "language")]
        public string Language { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recognitionState")]
        public string RecognitionState { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalTimeString")]
        public string TotalTimeString { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateCreated")]
        public System.DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateProcessed")]
        public System.DateTime? DateProcessed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateUpdated")]
        public System.DateTime? DateUpdated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "audioSourceVersion")]
        public int? AudioSourceVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "audioSource")]
        public AudioSource AudioSource { get; set; }

    }
}
