// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RewriteMe.Domain.WebApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FileContentResult
    {
        /// <summary>
        /// Initializes a new instance of the FileContentResult class.
        /// </summary>
        public FileContentResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FileContentResult class.
        /// </summary>
        public FileContentResult(byte[] fileContents = default(byte[]), string contentType = default(string), string fileDownloadName = default(string), System.DateTime? lastModified = default(System.DateTime?), EntityTagHeaderValue entityTag = default(EntityTagHeaderValue), bool? enableRangeProcessing = default(bool?))
        {
            FileContents = fileContents;
            ContentType = contentType;
            FileDownloadName = fileDownloadName;
            LastModified = lastModified;
            EntityTag = entityTag;
            EnableRangeProcessing = enableRangeProcessing;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileContents")]
        public byte[] FileContents { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contentType")]
        public string ContentType { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileDownloadName")]
        public string FileDownloadName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastModified")]
        public System.DateTime? LastModified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entityTag")]
        public EntityTagHeaderValue EntityTag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "enableRangeProcessing")]
        public bool? EnableRangeProcessing { get; set; }

    }
}
