// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RewriteMe.Domain.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LanguageVersion
    {
        /// <summary>
        /// Initializes a new instance of the LanguageVersion class.
        /// </summary>
        public LanguageVersion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LanguageVersion class.
        /// </summary>
        public LanguageVersion(System.Guid id, System.Guid informationMessageId, string title, string message, string description, string languageString, bool sentOnOsx, bool sentOnAndroid)
        {
            Id = id;
            InformationMessageId = informationMessageId;
            Title = title;
            Message = message;
            Description = description;
            LanguageString = languageString;
            SentOnOsx = sentOnOsx;
            SentOnAndroid = sentOnAndroid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "informationMessageId")]
        public System.Guid InformationMessageId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languageString")]
        public string LanguageString { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sentOnOsx")]
        public bool SentOnOsx { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sentOnAndroid")]
        public bool SentOnAndroid { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Title == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Title");
            }
            if (Message == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Message");
            }
            if (Description == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Description");
            }
            if (LanguageString == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "LanguageString");
            }
        }
    }
}
