// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RewriteMe.Domain.WebApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LastUpdates
    {
        /// <summary>
        /// Initializes a new instance of the LastUpdates class.
        /// </summary>
        public LastUpdates()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LastUpdates class.
        /// </summary>
        public LastUpdates(int? fileItem = default(int?), int? audioSource = default(int?), int? transcribeItem = default(int?))
        {
            FileItem = fileItem;
            AudioSource = audioSource;
            TranscribeItem = transcribeItem;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileItem")]
        public int? FileItem { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "audioSource")]
        public int? AudioSource { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transcribeItem")]
        public int? TranscribeItem { get; set; }

    }
}
