// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RewriteMe.Domain.WebApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RegisterUserModel
    {
        /// <summary>
        /// Initializes a new instance of the RegisterUserModel class.
        /// </summary>
        public RegisterUserModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RegisterUserModel class.
        /// </summary>
        public RegisterUserModel(System.Guid? id = default(System.Guid?), System.Guid? applicationId = default(System.Guid?), string email = default(string), string givenName = default(string), string familyName = default(string))
        {
            Id = id;
            ApplicationId = applicationId;
            Email = email;
            GivenName = givenName;
            FamilyName = familyName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationId")]
        public System.Guid? ApplicationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "givenName")]
        public string GivenName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "familyName")]
        public string FamilyName { get; set; }

    }
}
