// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace RewriteMe.Domain.WebApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TranscribeItem
    {
        /// <summary>
        /// Initializes a new instance of the TranscribeItem class.
        /// </summary>
        public TranscribeItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TranscribeItem class.
        /// </summary>
        public TranscribeItem(System.Guid? id = default(System.Guid?), System.Guid? fileItemId = default(System.Guid?), IList<RecognitionAlternative> alternatives = default(IList<RecognitionAlternative>), string userTranscript = default(string), byte[] source = default(byte[]), string startTime = default(string), string endTime = default(string), string totalTime = default(string), System.DateTime? dateCreated = default(System.DateTime?), System.DateTime? dateUpdated = default(System.DateTime?))
        {
            Id = id;
            FileItemId = fileItemId;
            Alternatives = alternatives;
            UserTranscript = userTranscript;
            Source = source;
            StartTime = startTime;
            EndTime = endTime;
            TotalTime = totalTime;
            DateCreated = dateCreated;
            DateUpdated = dateUpdated;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileItemId")]
        public System.Guid? FileItemId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alternatives")]
        public IList<RecognitionAlternative> Alternatives { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userTranscript")]
        public string UserTranscript { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public byte[] Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startTime")]
        public string StartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endTime")]
        public string EndTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalTime")]
        public string TotalTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateCreated")]
        public System.DateTime? DateCreated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateUpdated")]
        public System.DateTime? DateUpdated { get; set; }

    }
}
